# [Info]
# 左上角标题
site_name: ysue1933
site_url: https://ysue1933.github.io
site_author: Yishu Zhang
site_description: portfolio

# [Navigtion]
nav:
  - 我:
    - 游戏:
    - 其他:
  - 研究:
  - 网站:
    # 访客打开网站第一个看到的是 docs/index.md
    # 构建网站时，不用管报错 "The following pages exist in the docs directory, but are not included in the "nav" configuration: index.md"
    # 如果访客之后想要重新看到这个界面，可以在 docs/WEBSITE/index.md 找到